version: '3'

services:
  web:
    build: .
    command: python src/app.py runserver 0.0.0.0:5000
    volumes:
      - .:/code
    ports:
      - "5000:5000"
      
  web2:
    build: .
    command: python srvc2/app.py
    ports:
      - "80:5000"
    volumes:
      - .:/code

